# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://zww999.github.io/xiaomaomi.github.io/.'
baseurl: ''
title: 'xiaomaomi Lab'
description: '快乐五小只'
permalink: pretty
logo: 

# Pagination
paginate: 5
paginate_path: news/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: KEAIDUO
  url: /keaiduo/
- title: QIAOLEZI
  url: /qiaolezi/
- title: DATOUZI
  url: /datouzi/
- title: XIAOBINGGAN
  url: /xiaobinggan/
- title: WWCAT
  url: /wwcat/
# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    output: true
    description: "<b>Notable events in the 小猫咪 Lab</b>"
    feature_text: |
      ## <span style="color:white">News</span>
    feature_image: "https://huffordlab.github.io/pictures/maize.jpg"
